# Generated by Django 5.2.1 on 2025-06-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='phone',
            field=models.CharField(default=None, null=True),
        ),
    ]
