# Generated by Django 5.2.1 on 2025-06-15 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_order_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('client_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя клиента')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='Фотография')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'Ужасно'), (2, 'Плохо'), (3, 'Нормально'), (4, 'Хорошо'), (5, 'Отлично')], default=5, verbose_name='Оценка')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.master', verbose_name='Мастер')),
            ],
        ),
    ]
