# Generated by Django 5.2.1 on 2025-06-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('duration', models.PositiveIntegerField(default=20, help_text='Время выполнения в минутах', verbose_name='Длительность')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярная услуга')),
            ],
        ),
    ]
