# Generated by Django 5.2.1 on 2025-07-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_order_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ai_checked_status',
            field=models.CharField(choices=[('ai_checked_true', 'Проверено'), ('ai_checked_in_progress', 'В процессе проверки'), ('ai_checked_false', 'Не проверено')], default='ai_checked_false', max_length=30, verbose_name='Статус ИИ'),
        ),
    ]
